///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Mathemeatics
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MathemeaticsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("28d655f1-4564-4728-ad52-37dfa9766cd4")]
    public partial class MathemeaticsRepository : RepoGenBaseFolder
    {
        static MathemeaticsRepository instance = new MathemeaticsRepository();
        MathemeaticsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        MathemeaticsRepositoryFolders.OpenSnapXRoutineAppFolder _opensnapxroutine;
        MathemeaticsRepositoryFolders.MathSTANotepadAppFolder _mathstanotepad;

        /// <summary>
        /// Gets the singleton class instance representing the MathemeaticsRepository element repository.
        /// </summary>
        [RepositoryFolder("28d655f1-4564-4728-ad52-37dfa9766cd4")]
        public static MathemeaticsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MathemeaticsRepository() 
            : base("MathemeaticsRepository", "/", null, 0, false, "28d655f1-4564-4728-ad52-37dfa9766cd4", ".\\RepositoryImages\\MathemeaticsRepository28d655f1.rximgres")
        {
            _snapxuntitled = new MathemeaticsRepositoryFolders.SnapXUntitledAppFolder(this);
            _opensnapxroutine = new MathemeaticsRepositoryFolders.OpenSnapXRoutineAppFolder(this);
            _mathstanotepad = new MathemeaticsRepositoryFolders.MathSTANotepadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("28d655f1-4564-4728-ad52-37dfa9766cd4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("ccf92206-af50-4136-9952-698b41b49f95")]
        public virtual MathemeaticsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The OpenSnapXRoutine folder.
        /// </summary>
        [RepositoryFolder("355f3ab4-d94d-49c1-bfa1-85e2d66b36a7")]
        public virtual MathemeaticsRepositoryFolders.OpenSnapXRoutineAppFolder OpenSnapXRoutine
        {
            get { return _opensnapxroutine; }
        }

        /// <summary>
        /// The MathSTANotepad folder.
        /// </summary>
        [RepositoryFolder("e01a7f7d-9603-4644-9644-02c95b7d8d97")]
        public virtual MathemeaticsRepositoryFolders.MathSTANotepadAppFolder MathSTANotepad
        {
            get { return _mathstanotepad; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class MathemeaticsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("ccf92206-af50-4136-9952-698b41b49f95")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snapxuntitledInfo;
            RepoItemInfo _buttonokInfo;            
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "ccf92206-af50-4136-9952-698b41b49f95", "")
            {
                _snapxuntitledInfo = new RepoItemInfo(this, "SnapXUntitled", "titlebar[@accessiblerole='TitleBar']", 30000, null, "ba419d41-c69c-48d1-9428-1fa124397ddb");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container/form//button[@text='&OK' and @controlid='1148']", 30000, null, "d1f7f33d-2726-4f36-88b2-45264cc236a8");               
                _finishInfo = new RepoItemInfo(this, "Finish", "container/form/?/?/element/element/container/button[@text='Finish' and @controlid='3165']", 30000, null, "9ea4a455-c5f6-44e0-9ddb-3a5225feb9d4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ccf92206-af50-4136-9952-698b41b49f95")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ccf92206-af50-4136-9952-698b41b49f95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnapXUntitled item.
            /// </summary>
            [RepositoryItem("ba419d41-c69c-48d1-9428-1fa124397ddb")]
            public virtual Ranorex.TitleBar SnapXUntitled
            {
                get
                {
                    return _snapxuntitledInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The SnapXUntitled item info.
            /// </summary>
            [RepositoryItemInfo("ba419d41-c69c-48d1-9428-1fa124397ddb")]
            public virtual RepoItemInfo SnapXUntitledInfo
            {
                get
                {
                    return _snapxuntitledInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("d1f7f33d-2726-4f36-88b2-45264cc236a8")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("d1f7f33d-2726-4f36-88b2-45264cc236a8")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }           

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("9ea4a455-c5f6-44e0-9ddb-3a5225feb9d4")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("9ea4a455-c5f6-44e0-9ddb-3a5225feb9d4")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

        /// <summary>
        /// The OpenSnapXRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("355f3ab4-d94d-49c1-bfa1-85e2d66b36a7")]
        public partial class OpenSnapXRoutineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1148Info;

            /// <summary>
            /// Creates a new OpenSnapXRoutine  folder.
            /// </summary>
            public OpenSnapXRoutineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenSnapXRoutine", "/form[@title='Open Snap-X Routine']", parentFolder, 30000, null, true, "355f3ab4-d94d-49c1-bfa1-85e2d66b36a7", "")
            {
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", 30000, null, "9c021e9b-b98f-464c-a374-8b08d9242a64");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("355f3ab4-d94d-49c1-bfa1-85e2d66b36a7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("355f3ab4-d94d-49c1-bfa1-85e2d66b36a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("9c021e9b-b98f-464c-a374-8b08d9242a64")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("9c021e9b-b98f-464c-a374-8b08d9242a64")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }
        }

        /// <summary>
        /// The MathSTANotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("e01a7f7d-9603-4644-9644-02c95b7d8d97")]
        public partial class MathSTANotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new MathSTANotepad  folder.
            /// </summary>
            public MathSTANotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MathSTANotepad", "/form[@title='Math.STA - Notepad']", parentFolder, 30000, null, true, "e01a7f7d-9603-4644-9644-02c95b7d8d97", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "ba80f494-2b1f-4e14-8568-80b095c7222c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e01a7f7d-9603-4644-9644-02c95b7d8d97")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e01a7f7d-9603-4644-9644-02c95b7d8d97")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("ba80f494-2b1f-4e14-8568-80b095c7222c")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("ba80f494-2b1f-4e14-8568-80b095c7222c")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

    }
#pragma warning restore 0436
}